# Generated by Django 5.2.16 on 2026-07-26 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_txn_id', models.CharField(db_index=True, max_length=64)),
                ('transaction_status', models.CharField(max_length=30)),
                ('raw_payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cards.giftcard')),
            ],
            options={
                'verbose_name': 'Event Pembayaran',
                'verbose_name_plural': 'Event Pembayaran',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('gateway_txn_id', 'transaction_status'), name='unique_txn_status')],
            },
        ),
    ]
