# Generated by Django 5.2.16 on 2026-07-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LynkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('message_id', models.CharField(blank=True, max_length=120)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('items', models.CharField(blank=True, max_length=200, verbose_name='Produk')),
                ('item_total', models.PositiveIntegerField(default=0, verbose_name='Harga barang')),
                ('grand_total', models.IntegerField(default=0, verbose_name='Diterima penjual')),
                ('credits_total', models.PositiveSmallIntegerField(default=1, verbose_name='Kuota')),
                ('credits_used', models.PositiveSmallIntegerField(default=0, verbose_name='Terpakai')),
                ('raw_payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Lynk',
                'verbose_name_plural': 'Order Lynk',
                'ordering': ['-received_at'],
            },
        ),
    ]
