# Generated by Django 5.2.16 on 2026-07-26 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('birthday', 'Ulang Tahun'), ('anniversary', 'Anniversary'), ('love_story', 'Love Story'), ('proposal', 'Lamaran')], max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=80)),
                ('recipient_name', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Menunggu bayar'), ('paid', 'Lunas'), ('expired', 'Kedaluwarsa')], db_index=True, default='draft', max_length=10)),
                ('amount', models.PositiveIntegerField(default=15000)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kartu',
                'verbose_name_plural': 'Kartu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('birthday', 'Ulang Tahun'), ('anniversary', 'Anniversary'), ('love_story', 'Love Story'), ('proposal', 'Lamaran')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Template',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GiftPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cards/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cards.giftcard')),
            ],
            options={
                'verbose_name': 'Foto Kartu',
                'verbose_name_plural': 'Foto Kartu',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='giftcard',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.template'),
        ),
    ]
