# Generated by Django 5.2.16 on 2026-07-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='affirmations',
            field=models.TextField(blank=True, help_text='Satu kalimat per baris.'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='favorite_flower',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='giftphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
