# Generated by Django 5.2.16 on 2026-07-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_giftcard_affirmations_giftcard_favorite_flower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='comped',
            field=models.BooleanField(default=False, verbose_name='Gratis (pemilik)'),
        ),
    ]
