# Generated by Django 5.2.16 on 2026-07-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_giftcard_comped'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='style',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
