# Generated by Django 5.2.16 on 2026-07-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_giftcard_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftphoto',
            name='slot',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
