# Generated by Django 5.2.16 on 2026-07-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_giftphoto_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='texts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
