# Generated by Django 5.2.16 on 2026-07-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_giftcard_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='spotify_track_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
