# Generated by Django 5.2.16 on 2026-07-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_giftcard_slug_giftcard_spotify_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='track_artist',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='track_cover_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='track_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
