# Generated by Django 5.2.16 on 2026-07-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_giftcard_track_artist_giftcard_track_cover_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='qr_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='qr_string',
            field=models.TextField(blank=True),
        ),
    ]
