# Generated by Django 5.2.16 on 2026-07-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_giftcard_qr_image_url_giftcard_qr_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='Catatan pembeli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_code', to='cards.giftcard')),
            ],
            options={
                'verbose_name': 'Kode Akses',
                'verbose_name_plural': 'Kode Akses',
                'ordering': ['-created_at'],
            },
        ),
    ]
